WaterPipes = WaterPipes or {}
WaterPipes.Router = WaterPipes.Router or {}

require "WaterPipes/Constants"
require "WaterPipes/PipeObjectUtils"

local Constants = WaterPipes.Constants
local PipeObjectUtils = WaterPipes.PipeObjectUtils
local Router = WaterPipes.Router

-- A fluid router is a floor pipe flagged in modData, and it is two devices in one depending on what
-- sits on its tile:
--   * bare      -> an inline PRESSURE-REDUCING VALVE. A draw reaches through it to the upstream
--                  network (one way: OUT side back to IN side, never the reverse), and whatever it
--                  feeds runs at min(incoming head, ceiling).
--   * with a tank (the purifier) -> a HARD BOUNDARY. The fluid is being transformed there, so the
--                  two sides must never see each other, and water crosses only through that tank.
-- The crossing itself lives in NetworkAccess (it is a property of the walk); this module owns the
-- router's identity, its IN->OUT direction and its ceiling.

local function getModData(worldObject)
    if not worldObject or not worldObject.getModData then
        return nil
    end
    local ok, modData = pcall(worldObject.getModData, worldObject)
    return ok and modData or nil
end

function Router.isRouter(worldObject)
    local modData = getModData(worldObject)
    return modData and modData[Constants.ROUTER_MODDATA_KEY] == true or false
end

-- Straight pipe with a green(IN)/red(OUT) band, keyed by the OUT direction (atlas cells 32-35,
-- generated by tools/texturepack/gen_pipes.py -- repack the .pack for these to render).
local DIR_SPRITE = {
    N = "waterpipes_01_32",
    E = "waterpipes_01_33",
    S = "waterpipes_01_34",
    W = "waterpipes_01_35",
}

function Router.spriteForDirection(dir)
    return DIR_SPRITE[dir] or Constants.ROUTER_SPRITE
end

function Router.spriteFor(worldObject)
    return Router.spriteForDirection(Router.getDirection(worldObject))
end

function Router.findOnSquare(square)
    if not square then
        return nil
    end
    for _, worldObject in ipairs(PipeObjectUtils.getPipeObjectsOnSquare(square)) do
        if Router.isRouter(worldObject) then
            return worldObject
        end
    end
    return nil
end

function Router.hasRouterOnSquare(square)
    return Router.findOnSquare(square) ~= nil
end

-- ===== Direction (IN -> OUT) =====
-- The stored direction is the OUT side. Isometric mapping matches PipeAutotile: N=-y, E=+x, S=+y, W=-x.
local DIR_OFFSET = {
    N = { dx = 0, dy = -1 },
    E = { dx = 1, dy = 0 },
    S = { dx = 0, dy = 1 },
    W = { dx = -1, dy = 0 },
}

local function isValidDirection(dir)
    return dir == "N" or dir == "E" or dir == "S" or dir == "W"
end

function Router.getDirection(worldObject)
    local modData = getModData(worldObject)
    local dir = modData and modData[Constants.ROUTER_DIRECTION_KEY]
    if isValidDirection(dir) then
        return dir
    end
    return Constants.ROUTER_DEFAULT_DIRECTION
end

-- {dx,dy} of the OUT side; the IN side is the opposite.
function Router.getOutOffset(worldObject)
    return DIR_OFFSET[Router.getDirection(worldObject)]
end

-- ===== Pressure regulation =====
-- A router already stops pressure crossing it, which makes it the one place a player can put a
-- ceiling on a zone. Set it from the context menu; the setting is the head AT THE VALVE OUTLET, and
-- from there the water loses head over distance and height like any other run -- so a branch does not
-- sit at the setting all the way to its far end. The arithmetic is Pressure.atRegulator; this module
-- only stores the number. It can only ever REDUCE: the unregulated head is always one of the terms
-- the consumer takes the minimum of, so setting 25 on a line carrying 10 still gives 10. Pumps
-- BEHIND the valve stay behind it; a pump in front of it re-pressurises its own branch.

function Router.getPressureCeiling(worldObject)
    local modData = getModData(worldObject)
    local value = modData and modData[Constants.ROUTER_PRESSURE_KEY]
    if type(value) == "number" and value >= 0 then
        return value
    end
    return nil   -- unset: pass the incoming head straight through
end

function Router.setPressureCeiling(worldObject, value)
    local modData = getModData(worldObject)
    if not modData then
        return
    end
    if type(value) ~= "number" or value < 0 then
        modData[Constants.ROUTER_PRESSURE_KEY] = Constants.ROUTER_PRESSURE_UNSET
    else
        modData[Constants.ROUTER_PRESSURE_KEY] =
            math.min(math.max(value, 0), Constants.ROUTER_PRESSURE_MAX)
    end
    if worldObject.transmitModData then
        pcall(worldObject.transmitModData, worldObject)
    end

    -- The ceiling is baked into the regulator chains the network walk builds, so a cached walk still
    -- prices the old setting. Resolved off the WaterPipes table rather than required at the top:
    -- NetworkAccess already requires this module, and closing that loop is a recursive require.
    local NetworkAccess = WaterPipes.NetworkAccess
    if NetworkAccess and NetworkAccess.invalidateTraversalCache then
        NetworkAccess.invalidateTraversalCache()
    end
end

return Router
