WaterPipes = WaterPipes or {}
WaterPipes.Router = WaterPipes.Router or {}

require "WaterPipes/Constants"
require "WaterPipes/PipeObjectUtils"

local Constants = WaterPipes.Constants
local PipeObjectUtils = WaterPipes.PipeObjectUtils
local Router = WaterPipes.Router

-- A fluid router is a floor pipe flagged in modData. It is a network BOUNDARY: the graph and the
-- gravity traversal never conduct through it, so the IN-side pipes and OUT-side pipes stay two
-- separate networks. The active IN->container->OUT transfer (with the direction) lands in step 4.

local function getModData(worldObject)
    if not worldObject or not worldObject.getModData then
        return nil
    end
    local ok, modData = pcall(worldObject.getModData, worldObject)
    return ok and modData or nil
end

function Router.isRouter(worldObject)
    local modData = getModData(worldObject)
    return modData and modData[Constants.ROUTER_MODDATA_KEY] == true or false
end

-- Straight pipe with a green(IN)/red(OUT) band, keyed by the OUT direction (atlas cells 32-35,
-- generated by tools/texturepack/gen_pipes.py -- repack the .pack for these to render).
local DIR_SPRITE = {
    N = "waterpipes_01_32",
    E = "waterpipes_01_33",
    S = "waterpipes_01_34",
    W = "waterpipes_01_35",
}

function Router.spriteForDirection(dir)
    return DIR_SPRITE[dir] or Constants.ROUTER_SPRITE
end

function Router.spriteFor(worldObject)
    return Router.spriteForDirection(Router.getDirection(worldObject))
end

function Router.findOnSquare(square)
    if not square then
        return nil
    end
    for _, worldObject in ipairs(PipeObjectUtils.getPipeObjectsOnSquare(square)) do
        if Router.isRouter(worldObject) then
            return worldObject
        end
    end
    return nil
end

function Router.hasRouterOnSquare(square)
    return Router.findOnSquare(square) ~= nil
end

-- ===== Direction (IN -> OUT) =====
-- The stored direction is the OUT side. Isometric mapping matches PipeAutotile: N=-y, E=+x, S=+y, W=-x.
local DIR_OFFSET = {
    N = { dx = 0, dy = -1 },
    E = { dx = 1, dy = 0 },
    S = { dx = 0, dy = 1 },
    W = { dx = -1, dy = 0 },
}

local function isValidDirection(dir)
    return dir == "N" or dir == "E" or dir == "S" or dir == "W"
end

function Router.getDirection(worldObject)
    local modData = getModData(worldObject)
    local dir = modData and modData[Constants.ROUTER_DIRECTION_KEY]
    if isValidDirection(dir) then
        return dir
    end
    return Constants.ROUTER_DEFAULT_DIRECTION
end

-- {dx,dy} of the OUT side; the IN side is the opposite.
function Router.getOutOffset(worldObject)
    return DIR_OFFSET[Router.getDirection(worldObject)]
end

return Router
